# -*- coding: utf-8 -*-
"""pooja1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNMkv8ydyAtWUkphGcoA8qOqlmy58Hc3
"""

a=3
b=4
c=a+b
print(c)